### ISSUE TITLE
Yêu cầu - Cập nhật License

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/DH.HIS#2]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77150`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Medic Sài Gòn 5**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Cập nhật bổ sung DLL License: mabvdk  = "77150".

```

**Comment by ongtrieuhau** [comment]
Cập nhật:
- Admin: [v3.22.0721.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/7f02f365db5ec419d54ab6be4ebf56cd873665fe)
- Printer: [v3.22.0721.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/f041af1c6807c3374df18e21488ace490b3756b6)
- Fees: [v3.22.0721.1](https://github.com/dh-hos/dhg.hospitalfees/commit/565213026b885a1ff27571142a1452cacfcb6400)
- Services: [v3.22.0721.1](https://github.com/dh-hos/dhg.hospitalservices/commit/8b07b19eb6fc0684086eb030286b6f279e396ad5)

**Comment by nghivanbi** [comment]
Cập nhật:
+ Register: [](http://www.fsend.vn/download/9mdzLiiLDgjyFCBVmZgvIjlWXIH7odQZ)
