### ISSUE TITLE
Yêu cầu - Xây dựng webservices hỗ trợ việc liên kết chữ ký số.

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/DH.HIS#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Xây dựng webservices hỗ trợ việc liên kết chữ ký số.
- Tài liệu liên kết: Softdream, VNPT, Viettel...
- Trưởng dự án (TDA): Hậu. 
- Trách nhiệm TDA : lựa chọn công nghệ và phân công công việc cho thành viên dự án, báo cáo tình hình dự án.
- Thành phần: Hậu, Thống.
- Chức năng: thực hiện ký số cho các phân hệ khi cần.
```

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/DH.HIS/assets/155862740/35d86ace-cd66-4952-ac19-965deb794319)
