### ISSUE TITLE
Yêu cầu - Bổ sung thông tin License (DLL), cập nhật các phân hệ hỗ trợ bệnh viện mới.

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/DH.HIS#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN DA LIỄU ĐỒNG THÁP**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
SỞ Y TẾ ĐỒNG THÁP
Mã BV 87190
BỆNH VIỆN DA LIỄU ĐỒNG THÁP
Địa chỉ: 396, Lê Đại Hành, TP Cao Lãnh, Tỉnh Đồng Tháp
Điện thoại: 0277 3851525

Hạn hoàn thành: 28/09/2022. 


```

**Comment by ongtrieuhau** [comment]
[Cập nhật License](https://github.com/dh-hos/oLibraries/commit/295260218d4c4d6cfea5e777bc359e18bf8f9efc)
Printer: [3.22.0928.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/7fe7d49e784e2ca970ac42d8272e11c3f32b6b2f)
Admin: [3.22.0928.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/4cb2c190512f44592aa8726eedad0a3b861aff36)
HRM: [3.22.0928.1](https://github.com/dh-hos/dhg.hrm/commit/632584f82842850c7cd7f329d04b6fff51046267)
Fees: [3.22.0928.1](https://github.com/dh-hos/dhg.hospitalfees/commit/885f0d8b774f886daacded78a0c5ac910ce05452)

**Comment by vuongdh** [comment]
Cập nhật License [Treat4.202200928v1](http://www.fsend.vn/download/Pwh106p6Y5yfzyRlzWCEwL0j21TFY8jF)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0928.3](http://www.fsend.vn/download/w8VD5b-T4sKWW0O7UnA0bHsjS056l1aj)
Prescription: [v3.22.0928.3](http://www.fsend.vn/download/yT9PAh4t5-I0XF_p1afhalLbrHP_U9qU)

**Comment by vinh-dh** [comment]
[Laboratory 29/09/2022](https://www.fshare.vn/file/SGLFZI8BO6K2)
[Diagnose 29/09/2022](https://www.fshare.vn/file/ODGXZYKOENSQ)
[Reports 29/09/2022](https://www.fshare.vn/file/H9LWJQP4562K)
